import bmemcached
import time

client = bmemcached.Client(('127.0.0.1:11211' ))
time.sleep(1)
client.set('Test1', 'Succeed')
time.sleep(1)
client.set('Hello', 'World')
time.sleep(3)
client.set('Pokemon', 'GOGOGO')
time.sleep(1)
client.set('Hello', 'Pokemon')
time.sleep(3)
print client.get('Hello')
time.sleep(1)
print client.get('Hello')
time.sleep(2)
print client.get('Pokemon')
time.sleep(1)
client.set('Pokemon', 'GOGOGO')
time.sleep(1)
client.set('Hello', 'World')
time.sleep(3)
print client.get('Pokeman')
time.sleep(4)
print client.get('Pokemon')